comments = ['Show!', 'Caramba!', 'Legal', 'Curti demais', 'Sensacional', 'Demais mesmo =D', 'Amei S2',
                    'Manowwwwww!!!', 'Loucura ;D', 'Sinistrooooo', 'É bom demais', 'Não tem coisa melhor',
                    'Muito bom kkkkk', 'hahaha =D', 'Melhor perfil de hoje, me segue também',
                    'Como pode? Muito legal!',
                    'impressionante =D', 'Nunca vi isso', 'Arrasou no Instagram',
                    'Abro o insta e vejo isso, sensacional',
                    'Ganhei meu dia!', 'Uauuuuuuu, perfeito!', 'fico feliz em ver isso hoje', 'Beautiful',
                    'Merece mil comentários', 'Merece mil curtidas essa foto', 'Best pic today ever',
                    'A melhor foto de hoje', 'Isso fala muito!', 'Original!', 'Perfect!!! =D',
                    'The best of today!!!', 'Que Legal', 'O que?? Sério que isso acontece?','Como você fez isso?',
                    'Cool, I like this!','Muito legal!!!','Maneiro, legal mesmo.','Daora mesmo',
                    'Gostei desse perfil, dá uma olhada no meu.', 'Conte sempre com minha visita rs']